approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  '@next/eslint-plugin-next@*':
    peerDependencies:
      eslint: '>=9.0.0'
  'eslint-plugin-perfectionist@*':
    peerDependencies:
      typescript: '>=4.8.4 <6.1.0'

yarnPath: .yarn/releases/yarn-4.18.0.cjs
