coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  hide_project_coverage: false
  layout: 'condensed_header, condensed_files, condensed_footer'
  require_changes: false

github_checks:
  annotations: true
